use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PannelKit_Example' do
  pod 'PannelKit', :path => '../'

  target 'PannelKit_Tests' do
    inherit! :search_paths

    
  end
end
